In [1]:
import numpy as np

In [2]:
# Question 1
grid = [117, 97, 83, 79, 71,
113, 90, 80, 76, 68,
93, 86, 78, 65, 60,
89, 84, 74, 64, 59,
83, 79, 68, 62, 58]
grid = np.array(grid)/255
grid

array([0.45882353, 0.38039216, 0.3254902 , 0.30980392, 0.27843137,
       0.44313725, 0.35294118, 0.31372549, 0.29803922, 0.26666667,
       0.36470588, 0.3372549 , 0.30588235, 0.25490196, 0.23529412,
       0.34901961, 0.32941176, 0.29019608, 0.25098039, 0.23137255,
       0.3254902 , 0.30980392, 0.26666667, 0.24313725, 0.22745098])

In [4]:
# Question 2
red = [117, 161, 138, 139, 117,
161, 152, 125, 134, 106,
146, 142, 123, 118, 101,
133, 140, 119, 110, 96,
138, 122, 112, 101, 94]

blue = [97, 86, 67, 72, 59,
86, 80, 57, 72, 51,
75, 75, 61, 60, 48,
67, 77, 60, 56, 47,
76, 62, 55, 48, 47]

green = [24, 21, 13, 27, 22,
18, 21, 8, 31, 20,
11, 20, 14, 22, 17,
6, 24, 16, 20, 17,
19, 12, 12, 14, 19]

# use the equation
# I = (0.21 * R + 0.72 * G + 0.07 * B)/255

I = (0.21 * np.array(red) + 0.72 * np.array(green) + 0.07 * np.array(blue))/255	
I

array([0.1907451 , 0.2154902 , 0.1687451 , 0.21047059, 0.17466667,
       0.20701961, 0.20643137, 0.14117647, 0.21764706, 0.15776471,
       0.17188235, 0.194     , 0.15756863, 0.17576471, 0.14435294,
       0.14486275, 0.20419608, 0.15964706, 0.16243137, 0.13996078,
       0.18815686, 0.15137255, 0.14121569, 0.13588235, 0.14396078])

In [8]:
#Question 3a - Normalize RGB Values: R′ = R/255, G′ = G/255, R′ = R/255.
red_d = np.array(red)/255
green_d = np.array(green)/255
blue_d = np.array(blue)/255

#Question 3b - Compute Cmax = max(R′, G′, B′), Cmin = min(R′, G′, B′) and ∆ = Cmax − Cmin.
Cmax = np.maximum(red_d, green_d, blue_d)
Cmin = np.minimum(red_d, green_d, blue_d)
delta = Cmax - Cmin

#Question 3c - Compute H
H= np.zeros(25)
for i in range(25):
    if delta[i] == 0:
        H[i] = 0
    elif Cmax[i] == red_d[i]:
        H[i] = 60 * (((green_d[i] - blue_d[i])/delta[i]) % 6)
    elif Cmax[i] == green_d[i]:
        H[i] = 60 * (((blue_d[i] - red_d[i])/delta[i]) + 2)
    elif Cmax[i] == blue_d[i]:
        H[i] = 60 * (((red_d[i] - green_d[i])/delta[i]) + 4)


#Question 3d - Compute S
S = np.zeros(25)
for i in range(25):
    if Cmax[i] == 0:
        S[i] = 0
    else:
        S[i] = delta[i]/Cmax[i]

#Question 3e - Compute V
V = Cmax
#Question 3f - Print H, S, V
V

array([0.09411765, 0.08235294, 0.05098039, 0.10588235, 0.08627451,
       0.07058824, 0.08235294, 0.03137255, 0.12156863, 0.07843137,
       0.04313725, 0.07843137, 0.05490196, 0.08627451, 0.06666667,
       0.02352941, 0.09411765, 0.0627451 , 0.07843137, 0.06666667,
       0.0745098 , 0.04705882, 0.04705882, 0.05490196, 0.0745098 ])